### ISSUE TITLE
AssertionError: Invalid device id

### ISSUE THREAD

**Issue by Adesoji1** [lixx2938/MegaDepth#47]
Traceback (most recent call last):
  File "/home/adesoji/MLOPS/MegaDepth/demo.py", line 18, in <module>
    model = create_model(opt)
  File "/home/adesoji/MLOPS/MegaDepth/models/models.py", line 5, in create_model
    model = HGModel(opt)
  File "/home/adesoji/MLOPS/MegaDepth/models/HG_model.py", line 18, in __init__
    model= torch.nn.parallel.DataParallel(model, device_ids = [0,1])
  File "/home/adesoji/Videos/ENTER/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 142, in __init__
    _check_balance(self.device_ids)
  File "/home/adesoji/Videos/ENTER/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 23, in _check_balance
    dev_props = _get_devices_properties(device_ids)
  File "/home/adesoji/Videos/ENTER/lib/python3.8/site-packages/torch/_utils.py", line 455, in _get_devices_properties
    return [_get_device_attr(lambda m: m.get_device_properties(i)) for i in device_ids]
  File "/home/adesoji/Videos/ENTER/lib/python3.8/site-packages/torch/_utils.py", line 455, in <listcomp>
    return [_get_device_attr(lambda m: m.get_device_properties(i)) for i in device_ids]
  File "/home/adesoji/Videos/ENTER/lib/python3.8/site-packages/torch/_utils.py", line 438, in _get_device_attr
    return get_member(torch.cuda)
  File "/home/adesoji/Videos/ENTER/lib/python3.8/site-packages/torch/_utils.py", line 455, in <lambda>
    return [_get_device_attr(lambda m: m.get_device_properties(i)) for i in device_ids]
  File "/home/adesoji/Videos/ENTER/lib/python3.8/site-packages/torch/cuda/__init__.py", line 312, in get_device_properties
    raise AssertionError("Invalid device id")
AssertionError: Invalid device id

**Comment by huacong** [comment]
> Traceback (most recent call last): File "/home/adesoji/MLOPS/MegaDepth/demo.py", line 18, in model = create_model(opt) File "/home/adesoji/MLOPS/MegaDepth/models/models.py", line 5, in create_model model = HGModel(opt) File "/home/adesoji/MLOPS/MegaDepth/models/HG_model.py", line 18, in **init** model= torch.nn.parallel.DataParallel(model, device_ids = [0,1]) File "/home/adesoji/Videos/ENTER/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 142, in **init** _check_balance(self.device_ids) File "/home/adesoji/Videos/ENTER/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 23, in _check_balance dev_props = _get_devices_properties(device_ids) File "/home/adesoji/Videos/ENTER/lib/python3.8/site-packages/torch/_utils.py", line 455, in _get_devices_properties return [_get_device_attr(lambda m: m.get_device_properties(i)) for i in device_ids] File "/home/adesoji/Videos/ENTER/lib/python3.8/site-packages/torch/_utils.py", line 455, in return [_get_device_attr(lambda m: m.get_device_properties(i)) for i in device_ids] File "/home/adesoji/Videos/ENTER/lib/python3.8/site-packages/torch/_utils.py", line 438, in _get_device_attr return get_member(torch.cuda) File "/home/adesoji/Videos/ENTER/lib/python3.8/site-packages/torch/_utils.py", line 455, in return [_get_device_attr(lambda m: m.get_device_properties(i)) for i in device_ids] File "/home/adesoji/Videos/ENTER/lib/python3.8/site-packages/torch/cuda/**init**.py", line 312, in get_device_properties raise AssertionError("Invalid device id") AssertionError: Invalid device id

It seems your cuda issue.

**Comment by eb-art** [comment]
You have to change line 18  in  HG_model.py up to you, for eg. device_ids = [0]
